Π2016176
ioniodi/sitegr pull request #108
Opened 2021-03-06 16:58 UTC by p16koub1

### Προσθήκη ΕΔΙΠ Προσωπικού : Σωτηροπούλου Άννα
closes #**84**

ΑΜ: Π2016176

### Προτεινόμενες Αλλαγές
-- Αλλαγή στο config.yml -> remote_theme: από το δικό μου fork

-- Προσθήκη του author Σωτηροπούλου Άννα, με κωδική ονομασία sotan στο αρχείο authors.yml

-- Δημιουργία item: sotan.md στον φάκελο _people

..

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-14 16:22 UTC, epidrome requested changes
delete your config.yml

2021-03-14 16:22 UTC, epidrome commented on all_collections/_people/sotan.md
> +"
double quote alone on a line?! why?

plz tidy up!

2021-03-14 18:07 UTC, dimpram requested changes
Πέρα από το σχόλιο έχεις και ένα conflict στο data/authors.yml που θα πρέπει να διορθωθεί. Δοκίμασε να το ελέγξεις με το vscode, διευκολύνει αρκετά αυτήν την διαδικασία (προφανώς μπορείς να το κάνεις με όποιον τρόπο θες)

2021-03-14 18:07 UTC, dimpram commented on _config.yml
> +remote_theme             : p16koub1/minimal-ionio
Με αυτή την αλλαγή, αν γίνει merge το PR σου, όλο το site θα βλέπει στο theme σου πράγμα που θα είναι καταστοφικό για το υπόλοιπο site. Πρέπει οπωσδήποτε να κάνεις revert αυτό το αρχείο στην αρχική του μορφή.

2021-03-15 23:22 UTC, provopoulos commented on _config.yml
> +remote_theme             : p16koub1/minimal-ionio
Ένα παράδειγμα με σωστή χρήση δομής είναι το PR #87

2021-03-21 17:13 UTC, dimpram commented
Εξακολουθείς να έχει conflict και επίσης δεν κάνει build το netlify σου. Ρίξε μια ματιά και εκεί για να είσαι σίγουρος

2021-03-30 14:48 UTC, NikosKar23 commented
Προτεινόμενες αλλαγές:
- Αλλαγή ονομασίας του Pull Request με πιο περιγραφικό τίτλο (Προσθήκη ΕΔΙΠ Προσωπικού : Σωτηροπούλου Άννα)
- Κάνε το closes στην περιγραφή του pull request να κλείνει το issue που είχες να ανοίξει

2021-04-21 08:50 UTC, epidrome requested changes
plz fix your commits according to the above comments by other reviewers!
1. closes
2. _authors.yml conflict

2021-05-21 05:26 UTC, closed without merging