Προσθήκη Ανακοίνωσης #51
ioniodi/sitegr pull request #116
Opened 2021-03-06 19:38 UTC by panagiotismouts

Δημιουργία ανακοίνωσης 2021-02-11-ekdilosi-endiaferontos-mitroo-foititwn-ethaae.md, αναμονή έγκρισης του αιτήματος ενσωμάτωσης.
Μουτσιούνας Παναγιώτης
ΑΜ : Π2018007
email: p18mout@ionio.gr

### Σχετικό Issue
closes #51 

### Προτεινόμενες Αλλαγές
-- Προσθήκη των pdf που βρίσκονται στη σελίδα του πανεπιστημίου :https://di.ionio.gr/gr/news/20208/

..

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-08 17:39 UTC, Haki-Malai commented
Καλησπέρα, δοκίμασε τις αλλαγές σου με το ανέβασμα του fork με τις αλλαγές σου, ευχαριστώ.

2021-03-09 20:01 UTC, panagiotismouts commented
Πρόσθεσα στα σχόλια του pull request μου, την ιστοσελίδα μου  στο Netlify, όπου έκανα assign το fork της σελίδας με την δική μου ανακοίνωση. Δουλεύει κανονικά.

2021-03-10 14:51 UTC, Haki-Malai commented
Αραξε θα το δουν τα μπος και λογικά θα το εγγρίνουν.

2021-03-20 16:34 UTC, dimpram reviewed
Καλή δουλεία αλλά τα pdf που αναφέρεις στις προτεινόμενες αλλαγές που φαίνονται?

2021-03-20 17:10 UTC, panagiotismouts commented
@dimpram Καλησπέρα. Δεν γνωρίζω πως να τα προσθέσω γιαυτό δεν τα προσθέσα και έβαλα στις Αλλαγές γιατι νομιζα πως εκει προτείναμε αλλαγές που δεν καταφέραμε να κάνουμε οι ίδιοι και που θεωρήσαμε πως θα έπρεπε να προστεθούν.

2021-03-20 17:11 UTC, panagiotismouts commented
Τα pdf υπάρχουν στο official site, στη σελίδα που φαίνεται πανω.

2021-03-20 17:18 UTC, epidrome requested changes

2021-03-20 17:18 UTC, epidrome commented on all_collections/_posts/2021-02-11-ekdilosi-endiaferontos-mitroo-foititwn-ethaae.md
> + - Γενικές Ανακοινώσεις
delete?

γιατί θεωρείς πως είναι "γενική" ανακοίνωση?

εγώ, ας πούμε, μπορώ να κάνω αίτηση?

2021-03-20 17:18 UTC, epidrome commented on all_collections/_posts/2021-02-11-ekdilosi-endiaferontos-mitroo-foititwn-ethaae.md
> + - Φοιτητικά Νέα
αυτήν την ετικέτα που την βρήκες?

οι ετικέτες πρέπει να μπαίνουν ακριβώς όπως είναι!!!

2021-03-20 17:19 UTC, epidrome commented
@panagiotismouts 
γιατί δεν βάζεις τα εξωτερικά αρχεία με λινκ? δες άλλες σχετικές ανακοινώσεις

2021-03-20 17:37 UTC, panagiotismouts commented on all_collections/_posts/2021-02-11-ekdilosi-endiaferontos-mitroo-foititwn-ethaae.md
> + - Γενικές Ανακοινώσεις
Έσβησα την ανακοίνωση και πρόσθεσα στη θέση της μια πιο ταιριαστή, "Προκηρύξεις" από τις διαθέσιμες, όπως φαίνονται στις οδηγίες : https://github.com/ioniodi/sitegr/wiki/Taxonomy

2021-03-20 17:39 UTC, panagiotismouts commented
Διόρθωσα τις ετικέτες με βάση τις [οδηγίες](https://github.com/ioniodi/sitegr/wiki/Taxonomy) και πρόσθεσα στο κάτω κάτω μέρος της σελίδας section με τα 2 αρχεία pdf και docx.

Η σελίδα στο Netlify : https://infallible-jackson-fecc97.netlify.app/posts/2021/02/11/ekdilosi-endiaferontos-mitroo-foititwn-ethaae/

2021-03-20 18:27 UTC, dimpram approved these changes

2021-03-20 20:36 UTC, provopoulos approved these changes
Σωστή χρήση της δομής και εμφανίζεται κανονικά στις ανακοινώσεις!

2021-03-30 12:27 UTC, epidrome approved these changes

2021-03-31 15:14 UTC, merged