2018015 1
ioniodi/sitegr pull request #121
Opened 2021-03-07 00:08 UTC by Efthimis015

Τζιάλλας Ευθύμιος Π2018015

Δημιουργία ανακοίνωσης 2021-01-21-prosklhsh-ekdhlwshs-endiaferontos.md

### Σχετικό Issue
closes #90

### Προτεινόμενες Αλλαγές
-- Προσθήκη της ανακοίνωσης "Πρόσκληση εκδήλωσης ενδιαφέροντος για την συγκρότηση άμισθης Επιτροπής Ισότητας των Φύλων (Ε.Ι.Φ.)". Βλέπε LINK [εδώ](https://gifted-franklin-e2fc15.netlify.app/posts/2021/01/21/prosklhsh-ekdhlwshs-endiaferontos/).

..

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-08 19:43 UTC, c15pati approved these changes

2021-03-19 19:06 UTC, epidrome requested changes

2021-03-19 19:06 UTC, epidrome commented on all_collections/_posts/2021-01-21-prosklhsh-ekdhlwshs-endiaferontos.md
> +  - Δραστηριότητες Μελών
Αποφάσεις Οργάνων

ποια δραστηριότητα μελών βλέπεις?!

2021-03-20 20:33 UTC, provopoulos approved these changes
Σωστή χρήση της δομής και εμφανίζεται κανονικά στις ανακοινώσεις. Υπάρχει διαφωνία στις ετικέτες. Με τις τελικές αλλαγές θα είναι έτοιμο προς ενσωμάτωση.

2021-03-22 18:38 UTC, Efthimis015 commented
Έκανα την αλλαγή που χρειάστηκε. Ελπίζω να είμαι εντάξει τώρα!

2021-03-30 12:28 UTC, epidrome commented on all_collections/_posts/2021-01-21-prosklhsh-ekdhlwshs-endiaferontos.md
> +  - Conference
conference?! try again!

2021-03-30 12:30 UTC, epidrome commented on all_collections/_posts/2021-01-21-prosklhsh-ekdhlwshs-endiaferontos.md
> +  - Conference
αν δεν μπορείς να εντοπίσεις την σωστή ετικέτα γιατί δεν ζητάς γνώμη από συναδέλφους σου? πχ αυτούς που έχουν κάνει αντίστοιχο πετυχημένο αίτημα

2021-03-30 12:30 UTC, epidrome requested changes
θέλει δουλειά!

2021-03-30 14:33 UTC, NikosKar23 commented
Προτεινόμενες αλλαγές:
- Αλλαγή ονόματος του Pull Request με το όνομα της ανακοίνωσης που γίνεται προσθήκη
- Αλλαγή του tag σε "Προκηρύξεις" ή σε "Γενικές Ανακοινώσεις"
- Προσθήκη του ΑΜ στην περιγραφή του Pull Request

2021-04-02 09:22 UTC, Efthimis015 commented
Done!

2021-04-02 09:38 UTC, epidrome approved these changes

2021-04-06 07:47 UTC, merged