Προσθήκη ανακοίνωσης
ioniodi/sitegr pull request #129
Opened 2021-03-07 14:08 UTC by polycarpos

Δημιουργία ανακοίνωσης
ΑΜ:Π2018199
Εmail:p17andr2@ionio.gr
Πολύκαρπος Ανδρέου

### Σχετικό Issue
closes #115 

### Προτεινόμενες Αλλαγές

..

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-08 17:37 UTC, Haki-Malai commented
Καλησπέρα, δοκίμασε τις αλλαγές σου με το ανέβασμα του fork με τις αλλαγές σου, ευχαριστώ.

2021-03-09 20:05 UTC, polycarpos commented
Πρόσθεσα το link του netlify και τρέχει κανονικά.

2021-03-10 11:41 UTC, polycarpos commented
άλλαξα τα tags σε φοιτητικά νέα και έργα

2021-03-10 17:03 UTC, c15pati approved these changes

2021-03-19 19:12 UTC, epidrome requested changes

2021-03-19 19:12 UTC, epidrome commented on all_collections/_posts/2020-11-27-dieukrinisi-akadimaikon-tautotiton.md
> + - Έργα
Φοιτητικά Έργα και Νέα

δεν πειράζουμε τις ετικέτες του γουήκι!!!

2021-03-19 19:13 UTC, epidrome commented
@c15pati τις ετικέτες τις κοιτάζεις? είδα μερικά αιτήματα τώρα και είχαν όλα πρόβλημα! και τους έχει δώσει θετικό, λίγο προσοχή παρακαλώ! γιατι μετά θα σκουπίζουμε (σκουπίδια)

2021-03-31 16:07 UTC, polycarpos commented on all_collections/_posts/2020-11-27-dieukrinisi-akadimaikon-tautotiton.md
> + - Έργα
@epidrome

2021-03-31 20:50 UTC, polycarpos commented on all_collections/_posts/2020-11-27-dieukrinisi-akadimaikon-tautotiton.md
> + - Έργα
@epidrome

2021-04-06 20:50 UTC, NikosKar23 reviewed
Προτεινόμενες Αλλαγές:
- Αλλαγή τίτλου pull request με τον τίτλο της ανακοίνωσης που προσθέτεις
- Προσθήκη link της ανακοίνωσης στην οποία αναφέρεσαι που βρίσκεται στο κανονικό site (di.ionio.gr)

2021-04-07 11:56 UTC, polycarpos commented
@NikosKar23

2021-04-09 15:07 UTC, epidrome approved these changes

2021-04-09 16:30 UTC, merged