2018171 add multimedia details
ioniodi/sitegr pull request #130
Opened 2021-03-07 14:30 UTC by perikarananou

Kαρανάνου Περιστέρα 
Π2018171

### Σχετικό Issue
closes#93

### Προτεινόμενες Αλλαγές
-- Αλλαγή 1 :Προσθήκη των στόχων του μαθήματος και τα μαθησιακά αποτελέσματα σύμφωνα με το επίσημο site

..

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-08 17:35 UTC, Haki-Malai commented
Καλησπέρα, δοκίμασε άμα οι αλλαγές σου δουλεύουν στο netlify και βάλε το λινκ. Επίσης, φτιάξε λιγο το λινκ για τον αριθμό του issue, κοίτα πως το κάνανε και οι άλλοι.

2021-03-08 19:31 UTC, c15pati commented
Πρέπει να φτιάξεις το closes ώστε όντως να κλείνει το αντίστοιχο Issue

2021-03-19 19:19 UTC, epidrome requested changes

2021-03-19 19:19 UTC, epidrome commented on all_collections/_courses/multimedia.md
> +excerpt:
μελέτησε λίγο την δομή των αρχείων YAML, δεν βάζουμε κενές γραμμές!!!
https://jekyllrb.com/docs/step-by-step/03-front-matter/#use-front-matter

2021-03-20 20:30 UTC, provopoulos commented on all_collections/_courses/multimedia.md
> +excerpt:
Υπάρχει κάποια εμφώλευση η οποία χαλάει τη δομή.

2021-03-23 18:04 UTC, perikarananou commented on all_collections/_courses/multimedia.md
> +excerpt:
Έχω κάνει κάποιες αλλαγές αλλά δεν τρέχει

2021-03-29 17:25 UTC, p15xiar commented
Βάλε ένα link από το δικό σου netlify Deploy

2021-03-30 12:38 UTC, epidrome approved these changes

2021-04-01 10:46 UTC, p15xiar approved these changes

2021-04-13 10:13 UTC, epidrome approved these changes

2021-04-18 23:48 UTC, provopoulos approved these changes
Σωστή η δομή ύστερα από τις αλλαγές.
Υποθέτω πως η @perikarananou εννοεί πως δεν λειτουργούν οι αλλαγές μέσω Github Pages το οποίο κι έχει διευκρινιστεί προηγουμένως.
Σε κάθε περίπτωση, έστησα ένα αντίγραφο του αποθετηρίου και οι προσθήκες του μαθήματος φαίνονται εδώ: https://optimistic-sammet-0279ca.netlify.app/courses/multimedia/

2021-04-18 23:48 UTC, merged