Προσθήκη Ανακοίνωσης "Τμήμα Πληροφορικής - Bi.H.E.Lab: Πρόγραμμα εξ Αποστάσεως Εκπαίδευσης «Ιατρική Ακριβείας με Χρήση Υπολογιστικών Βιοδεικτών»"
ioniodi/sitegr pull request #146
Opened 2021-03-09 20:32 UTC by p15kost

### Σχετικό Issue
closes #144 

### Προτεινόμενες Αλλαγές
-- Προσθήκη Ανακοίνωσης "Τμήμα Πληροφορικής - Bi.H.E.Lab: Πρόγραμμα εξ Αποστάσεως Εκπαίδευσης «Ιατρική Ακριβείας με Χρήση Υπολογιστικών Βιοδεικτών»"
[Netlify](https://jolly-nightingale-1c8cdd.netlify.app/posts/2020/10/25/iatrikh_akriveia_me_xrhsh_biodeiktwn/)

Χαράλαμπος Κωστάντης Π2015127

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-10 08:01 UTC, c15pati approved these changes

2021-03-19 19:36 UTC, epidrome requested changes

2021-03-19 19:36 UTC, epidrome commented on all_collections/_posts/2020-10-25-iatrikh_akriveia_me_xrhsh_biodeiktwn.md
> + - Έρευνα
Έρευνα???

2021-03-20 20:24 UTC, provopoulos commented on all_collections/_posts/2020-10-25-iatrikh_akriveia_me_xrhsh_biodeiktwn.md
> + - Έρευνα
@epidrome
Έχετε κάποια διαφωνία με την ετικέτα; Κι αν ναι, ποια προτείνετε ως αλλαγή;
Η αρχική ανακοίνωση βρίσκεται [εδώ](https://di.ionio.gr/gr/news/15573/).

2021-03-20 20:25 UTC, provopoulos approved these changes
Σωστή χρήση της δομής και εμφανίζεται κανονικά στις ανακοινώσεις.

2021-03-22 07:12 UTC, epidrome commented on all_collections/_posts/2020-10-25-iatrikh_akriveia_me_xrhsh_biodeiktwn.md
> + - Έρευνα
το ερώτημα είναι ποια ο συγγραφέας @p15kost θεωρεί πιο συμβατή με βάση το νόημα της ανακοίνωσης και τις διαθέσιμες ετικέτες, οι οποίες αν δεν το καλύπτουν θα μπορούσαν να επεκταθούν-τροποποιηθούν

σίγουρα πάντως δεν βλέπω κάποια "έρευνα"

2021-03-30 12:44 UTC, epidrome requested changes
δες σχόλια

2021-03-30 12:44 UTC, epidrome commented on all_collections/_posts/2020-10-25-iatrikh_akriveia_me_xrhsh_biodeiktwn.md
> +---
+ Μεταπτυχιακές Σπουδές

2021-03-30 12:44 UTC, epidrome commented on all_collections/_posts/2020-10-25-iatrikh_akriveia_me_xrhsh_biodeiktwn.md
> +Περισσότερες πληροφορίες για το Πρόγραμμα:
μαρκνταουν λινκ

2021-03-30 12:44 UTC, epidrome commented on all_collections/_posts/2020-10-25-iatrikh_akriveia_me_xrhsh_biodeiktwn.md
> +Ιστοχώρος Bi.H.E.Lab:
μαρκνταουν λινκ

2021-03-30 19:49 UTC, p15kost commented
Πρόσθεσα το ταγκ "Μεταπτυχιακές Σπουδές" που ταιριάζει καλύτερα και έκανα markdown τα λινκ κάτω κάτω. Πιστεύετε πως χρειάζεται κάτι άλλο;

2021-04-09 15:09 UTC, epidrome requested changes

2021-04-09 15:09 UTC, epidrome commented on all_collections/_posts/2020-10-25-iatrikh_akriveia_me_xrhsh_biodeiktwn.md
> +**Περισσότερες πληροφορίες για το Πρόγραμμα:**
μαρκνταουν λινκ

2021-04-09 15:09 UTC, epidrome commented on all_collections/_posts/2020-10-25-iatrikh_akriveia_me_xrhsh_biodeiktwn.md
> +**Ιστοχώρος Bi.H.E.Lab:**
μαρκνταουν λινκ

2021-04-13 10:15 UTC, epidrome approved these changes

2021-04-13 10:15 UTC, merged