Προσθήκη Ανακοίνωσης: "Αναστολή εισερχόμενης και εξερχόμενης κινητικότητας Εrasmus με φυσική παρουσία στις χώρες υποδοχής -φοιτητών & προσωπικού- εαρινού εξαμήνου ακαδ. έτους 2020-2021 λόγω της πανδημίας COVID-19"
ioniodi/sitegr pull request #148
Opened 2021-03-10 09:47 UTC by MariaXristinaPapatheodwrou

### Προσθήκη Ανακοίνωσης: "Αναστολή εισερχόμενης και εξερχόμενης κινητικότητας Εrasmus με φυσική παρουσία στις χώρες υποδοχής -φοιτητών & προσωπικού- εαρινού εξαμήνου ακαδ. έτους 2020-2021 λόγω της πανδημίας COVID-19"
closes #110 

### Προτεινόμενες Αλλαγές
-- Πιο συχνή ενημέρωση ανακοινώσεων 

### Υπενθυμίσεις
- [X] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [X] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [X] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-10 13:16 UTC, Haki-Malai commented
Δοκίμασε τις αλλαγές σου στο Netlify

2021-03-11 18:24 UTC, c15pati approved these changes

2021-03-21 15:13 UTC, MariaXristinaPapatheodwrou commented
> Δοκίμασε τις αλλαγές σου στο Netlify και πρόσθεσε το link.

https://wonderful-clarke-cffc37.netlify.app/posts/2021/02/12/epeigousa-anakoinwsi-erasmus/

2021-03-24 07:55 UTC, c15pati commented
To _config.yml γιατί το έχεις πειράξει?

2021-04-06 07:44 UTC, epidrome requested changes

2021-04-06 07:44 UTC, epidrome commented on all_collections/_posts/2021-02-12-epeigousa-anakoinwsi-erasmus.md
> + - Γενικές Ανακοινώσεις
Αποφάσεις Οργάνων?

2021-04-10 13:03 UTC, p15xiar approved these changes

2021-04-10 13:04 UTC, p15xiar approved these changes

2021-04-13 10:18 UTC, epidrome approved these changes

2021-04-13 10:18 UTC, merged