Προσθήκη της ανακοίνωσης "Κυκλοφόρησε το πρώτο τεύχος του ηλεκτρονικού ενημερωτικού δελτίου ionio" που δημοσιεύτηκε στις 09-02-2021 ώρα 10:52
ioniodi/sitegr pull request #156
Opened 2021-03-13 13:40 UTC by p16andr

### Σχετικό Issue
closes #40

### Προτεινόμενες Αλλαγές
-- Προσθήκη της ανακοίνωσης "Κυκλοφόρησε το πρώτο τεύχος του ηλεκτρονικού ενημερωτικού δελτίου ionio" που δημοσιεύτηκε στις 09-02-2021 ώρα 10:52

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-13 14:36 UTC, p16andr commented
Αλλαξα το branch και εβαλα εκει την ανακοινωση μου και εκανα ενα νεο pull request γιατι ενω ειχα κανει ολη την διαδικασια με το αλλο branch δεν εμφανιζοταν η ανακοινωση μου.

2021-03-15 08:43 UTC, c15pati approved these changes

2021-03-16 14:26 UTC, p16andr commented
@c15pati
Κυριε πατηνιωτη δεν μπορω να καταλαβω. Παλι δεν εμφανιζεται η ανακοινωση μου στην demo σελιδα μου στο netlify. 
Θα μπορουσατε να με βοηθησετε σας παρακαλω παρα μα παρα πολυ.

2021-03-20 10:30 UTC, epidrome commented
@c15pati φαίνεται πως μας στέλνει το δικό του κονφιγκ!? σε παρακαλώ λίγο προσοχή!!!

2021-03-20 16:46 UTC, dimpram requested changes
Θα μπορούσες να προσθέσεις link από το netlify preview σου?

2021-03-20 16:46 UTC, dimpram commented on _config.yml
> +remote_theme             : p16andr/minimal-ionio
Θα πρέπει να αλλάξεις αυτό το αρχείο στην αρχική του μορφή καθώς έτσι όπως είναι, αν γίνει merge στο sitegr, όλο το site θα έχει το δικό σου theme του minimal-ionio κάτι το οποίο θα είναι καταστροφικό

2021-03-22 17:28 UTC, p16andr commented on _config.yml
> +remote_theme             : p16andr/minimal-ionio
@dimpram @provopoulos 
Αλλαξα το config μου απλως συνεχιζω να εχω το προβλημα με το αιτημα ενσωματωσης ενω εχω ακολουθησει ολη την διαδικασια με το fork, το δικο μου branch και το issue κανονικα ολα και κανω deply απο το netlify την ανακοινωση μου και δεν μου ενφανιζει καθολου την ανακοινωση μου. Εχω δοκιμασει κιολας με αλλα branch αλλα και παλι δεν μου εμφανιζει την ανακοινωση μου. 

![2021-03-20 (2)](https://user-images.githubusercontent.com/72922731/112031886-7ca29980-8b44-11eb-891c-07f6273bb218.png)

2021-03-23 10:44 UTC, closed without merging

2021-03-23 12:55 UTC, p16andr commented
@dimpram
Επισης διεγραψα την ανακοινωση μου και ξαναεκανα ολη την διαδικασια με την προσθεση της ανακοινωσης απο τερματικο και εγινε κανονικα deply αλλα και παλι δεν μου εμφανιζεται η ανακοινωση μου.

2021-03-23 12:56 UTC, p16andr commented
Δεν μπορω να καταλαβω που εχει γινει το λαθος.

2021-03-29 17:29 UTC, NikosKar23 commented
Έχω κάποιες παρατηρήσεις που μπορεί να σε βοηθήσουν να λύσεις το πρόβλημα σου.

Προτεινόμενες αλλαγές στο αρχείο .md: 
- στο excerpt κλείσε τα εισαγωγικά που έχεις ανοίξει (ακριβώς πριν τα tags, πρέπει να κλείνουν)
-  Λίγο πριν το τέλος, εκεί που έχει τις 3 παύλες (---) υπάρχει ένα κενό. Κάνε ένα backspace
- Επίσης καλό θα ήταν στον τίτλο του αρχείου αντί για 09-02-2021, να χρησιμοποιήσεις την μορφολογία που υπάρχει στο site, δηλαδή πρώτα η χρονιά μετά ο μήνας και μετά η ημέρα. (Δηλ: 2021-02-09)

Ελπίζω να βοήθησα.

2021-03-30 10:18 UTC, p16andr commented
@NikosKar23 
Σε ευχαριστω πολύ. Με βοηθησες παρα πολυ.