Προσθήκη Ανακοίνωσης "Ανακοίνωση σχετικά με τις προκηρύξεις φοιτητικής κινητικότητας 2021-2022 & κινητικότητας προσωπικού 2020-2021"
ioniodi/sitegr pull request #169
Opened 2021-03-21 18:03 UTC by p14pall

### Σχετικό Issue
closes #158

### Προτεινόμενες Αλλαγές
-- Αλλαγή 1

-- Αλλαγή 2

..

### Υπενθυμίσεις
- [ ] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [ ] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [ ] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-29 17:01 UTC, p15xiar requested changes
Λείπει η προσθήκη του μαθήματος στην λίστα των μαθημάτων που εμφανίζεται : https://amazing-cori-4de1f3.netlify.app/courses/
#tip       
Άλλαξε το link που έχεις βάλει ώστε να ανακατευθύνει απευθείας στην σελίδα του μαθήματος που προσέθεσες ώστε να μην ψάχνουν και οι άλλοι reviewers οπως εγώ

2021-04-06 08:02 UTC, epidrome requested changes
delete the images!

2021-04-06 08:03 UTC, epidrome requested changes

2021-04-06 08:03 UTC, epidrome commented on all_collections/_posts/2020-11-19-prokyrikseis-foititikis-kinitikotitas.md
> + - Γενικές Ανακοινώσεις
delete?

2021-04-06 17:18 UTC, c15pati commented
https://github.com/ioniodi/sitegr/wiki/Taxonomy

2021-04-16 13:59 UTC, epidrome commented
@p14pall delete the images!!!

2021-04-16 13:59 UTC, closed without merging