Προσθήκη της ανακοίνωσης "Κυκλοφόρησε το πρώτο τεύχος του ηλεκτρονικού ενημερωτικού δελτίου @ionio!" που δημοσιεύτηκε στις 2021-02-09 ώρα 10:52
ioniodi/sitegr pull request #171
Opened 2021-03-30 10:27 UTC by p16andr

### Σχετικό Issue
closes #40 

[netlifylink](https://6062fa6da2780d0008991d0a--p16andr-576871.netlify.app/posts/2021/02/09/kykloforish-tou-prwtou-teuxous-tou-enhmerwtikou-deltiou-ioniou/)

### Προτεινόμενες Αλλαγές
-- Προσθήκη της ανακοίνωσης "Κυκλοφόρησε το πρώτο τεύχος του ηλεκτρονικού ενημερωτικού δελτίου @ionio!" που δημοσιεύτηκε στις 2021-02-09 ώρα 10:52
..

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-30 10:32 UTC, p16andr commented
@epidrome @c15pati 
Νταξει το ελυσα το θεμα με το αιτημα ενσωματωσης. Σας παραθετω κανονικα παραπανω το link οπου φαινεται η ανακοινωση μου στο demo μου

2021-03-30 12:22 UTC, epidrome commented
@p16andr 
σε παρακαλώ ενημέρωσε την σχετική συζήτηση με την λύση που βρήκες, ίσως βοηθήσει και άλλους
https://github.com/ioniodi/sitegr/discussions/166

2021-03-31 08:54 UTC, p15xiar commented on all_collections/_posts/2021-02-09-kykloforish-tou-prwtou-teuxous-tou-enhmerwtikou-deltiou-ioniou.md
>  **Μπορείτε να διαβάσετε το πρώτο newsletter μας, κατεβάζοντας το αρχείο από τον παρακάτω σύνδεσμο [Διαβάστε το πρώτο τεύχος του ηλεκτρονικού ενημερωτικού δελτίου @ionio!]https://ionio.gr/download.php
Το download Link θέλει μία διόρθωση.

2021-03-31 11:41 UTC, NikosKar23 requested changes
Κράτα το [Διαβάστε το πρώτο τεύχος του ηλεκτρονικού ενημερωτικού δελτίου @ionio!] που είχες γράψει, και βάλε το link μέσα σε μια παρένθεση ( ) για να λειτουργήσει.
Για να βεβαιωθείς ότι λειτουργεί πριν το κάνεις commit, μπορείς να πατήσεις Preview Changes.

2021-03-31 12:43 UTC, p16andr commented
@p15xiar
Φαινεται κανονικα το deploy preview στο επισημο site της σχολης
https://deploy-preview-171--epic-hamilton-da9ac8.netlify.app/posts/2021/02/09/kykloforish-tou-prwtou-teuxous-tou-enhmerwtikou-deltiou-ioniou/

2021-03-31 15:42 UTC, epidrome requested changes
1. γιατί σβήνεις ένα ποστ??
2. γιατί στέλνεις το δικό σου κονφιγκ???

2021-03-31 15:51 UTC, p15xiar commented
Η διόρθωση δεν θα γίνει από το depoly preview από το pull request αλλά από το link του δικού σου demo. Θα έχεις κάνει σωστά το αίτημα αλλά δεν θα πάρεις τον βαθμό που πρέπει σύμφωνα με τις οδηγίες.

2021-04-01 13:00 UTC, p15xiar commented
Μετά τις τελευταίες αλλαγές η ανακοίνωση δεν είναι ορατή στο deploy preview. Το δικό σου netlify link έχει μείνει γύρω στα 20 commits πίσω.

2021-04-02 08:56 UTC, p16andr commented
@p15xiar 
Πηγα να διορθωσω τις αλλαγες απο το file changed για να ξανακανω το pull request μου και να λυθει το προβλημα και παλι δεν μου εμφανιζοταν η ανακοινωση. Δεν μπορω να καταλαβω περαιτερω.

2021-04-02 09:35 UTC, p16andr commented
@epidrome 
Διορθωσα τις αλλαγες μου που επρεπε να κανω και εκανα update το netlifylink στο pull request. Νομιζω οτι τωρα δεν θα υπαρχει καποιο προβλημα.

2021-04-02 11:42 UTC, p15xiar approved these changes

2021-05-06 03:39 UTC, closed without merging