Demo branch
ioniodi/sitegr pull request #211
Opened 2021-04-30 17:55 UTC by p14ntot

### Σχετικό Issue
closes #151 

### Προτεινόμενες Αλλαγές
-- Προσθήκη ανακήνωσης:Εξέταση μαθημάτων για τους επι πτυχιο φοιτητές

ΑΜ Π2014148

[netlify](https://jovial-bardeen-80b084.netlify.app/posts/2021/04/30/eksetasi-mathimatwn-gia-tous-epi-ptyxio-foitites/)

..

### Υπενθυμίσεις
- [X] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [X] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [X] Έχω δημιουργήσει branch για τις αλλαγές

2021-05-02 11:02 UTC, epidrome requested changes
don't send your config. delete config

2021-05-12 08:44 UTC, c15pati approved these changes

2021-05-12 08:53 UTC, elias2500 approved these changes

2021-05-13 12:42 UTC, epidrome approved these changes

2021-05-13 12:42 UTC, merged