Προσθήκη Ανακοίνωσης.
ioniodi/sitegr pull request #35
Opened 2021-03-02 20:17 UTC by Miltos9

### Σχετικό Issue
closes #**issue**

### Προτεινόμενες Αλλαγές
--

--

..

### Υπενθυμίσεις
- [X] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [X] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-03 10:30 UTC, epidrome commented
issueNo = ?

βάλε τον αριθμό του αντίστοιχου θέματος!

2021-03-03 17:17 UTC, Miltos9 commented
Έβαλα τον αριθμό του θέματος στην αναφορά.

2021-03-03 18:56 UTC, epidrome requested changes
στις ετικέτες θα έβαζα

Έρευνα
Δραστηριότητες Μελών

2021-03-04 13:44 UTC, Miltos9 commented
άλλαξα τις ετικέτες σε :
Έρευνα
Δραστηριότητες Μελών

2021-03-04 18:31 UTC, epidrome approved these changes

2021-03-05 17:22 UTC, epidrome commented
@c15pati 

> requested review from epidrome and c15pati 2 days ago

2021-03-05 19:11 UTC, c15pati approved these changes

2021-03-06 07:11 UTC, merged