Ενημέρωση βιογραφικού στο προφίλ του καθηγητή Εμμανουήλ Μαραγκουδάκη
ioniodi/sitegr pull request #359
Opened 2022-03-22 18:21 UTC by KonstantinosTourtsakis

### Σχετικό Issue
closes #268 

### Συνεργάτες που θα κάνουν σχόλια ή θα αξιολογήσουν τις αλλαγές (κάντε mention @ τουλάχιστον δύο): @voltmaister @NickLitharis

### Προτεινόμενες Αλλαγές
-- Διόρθωση του βιογραφικού του καθηγητή Εμμανουήλ Μαραγκουδάκη στο αρχείο `sitegr/_data/authors.yml`. Στο βιογραφικό έλειπαν τα μαθήματα "Ανάκτηση Πληροφορίας" και "Επιστήμη των Δεδομένων" και έπρεπε να αφαιρεθεί το μάθημα "Δομές Δεδομένων".

#### Οι αλλαγές έγιναν στο branch `2019140` και εδώ βρίσκεται το link από το [demo](https://zen-goldstine-c1847a.netlify.app/people/mmarag/) της ιστοσελίδας με τις αλλαγές.

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2022-03-22 18:31 UTC, voltmaister approved these changes
Κοίταξα τις αλλαγές όλα φαίνεται να είναι εντάξει και δεν υπάρχει πιθανότητα να γίνει κάποιο θέμα με το site. Από εμένα περνάει.

2022-03-22 21:29 UTC, NickLitharis commented
Όλα δουλεύουν σωστά. Από εμένα έχει το πράσινο φως.

2022-03-22 21:30 UTC, NickLitharis reviewed
Όλα δουλεύουν σωστά. Από εμένα έχει το πράσινο φως.

2022-03-22 21:30 UTC, NickLitharis approved these changes
Όλα δουλεύουν σωστά. Από εμένα έχει το πράσινο φως.

2022-03-24 11:05 UTC, voltmaister approved these changes

2022-03-24 17:33 UTC, epidrome commented
@KonstantinosTourtsakis @voltmaister @NickLitharis 

δηλώνει ότι θα αλλάξει τα μαθήματα που βρίσκονται στις συλλογές

στέλνει αλλαγή για το γνωστικό αντικείμενο του καθηγητή εδώ

και σας φαίνεται σωστό;;

2022-03-24 17:49 UTC, KonstantinosTourtsakis commented
> @KonstantinosTourtsakis @voltmaister @NickLitharis
> 
> δηλώνει ότι θα αλλάξει τα μαθήματα που βρίσκονται στις συλλογές
> 
> στέλνει αλλαγή για το γνωστικό αντικείμενο του καθηγητή εδώ
> 
> και σας φαίνεται σωστό;;

Αρχικά θεώρησα πως ο "χώρος" στον οποίο εμφανίζονται οι πληροφορίες εκείνες στην ιστοσελίδα είναι ο χώρος στον οποίο υπάρχει ένα σύντομο βιογραφικό σχετικά με τον καθηγητή. Δεν γνώριζα ότι χρησημοποιούσα τον λάθος όρο. Θα μετονομάσω το pull request σε "Ενημέρωση γνωστικού αντικειμένου στο προφίλ του καθηγητή Εμμανουήλ Μαραγκουδάκη".

2022-03-24 17:50 UTC, voltmaister requested changes
Για να κάνεις αλλαγή στα μαθήματα πρέπει να κάνεις την αλλαγή στο courses και όχι στο author επίσης η αλλαγή σου υπάρχει ήδη στο site οπότε πρέπει να προτείνεις άλλη αλλαγή.
https://epic-hamilton-da9ac8.netlify.app/people/mmarag/

2022-03-25 13:55 UTC, epidrome commented
> Για να κάνεις αλλαγή στα μαθήματα πρέπει να κάνεις την αλλαγή στο courses και όχι στο author επίσης η αλλαγή σου υπάρχει ήδη στο site οπότε πρέπει να προτείνεις άλλη αλλαγή.
> 
> https://epic-hamilton-da9ac8.netlify.app/people/mmarag/

αυτό το σχόλιο θα έπρεπε να είχε γίνει στο αντίστοιχο θέμα, ποτέ δεν είναι αργά..

2022-03-25 20:16 UTC, closed without merging