2019027 pull2
ioniodi/sitegr pull request #400
Opened 2022-04-17 10:04 UTC by p19zing

### Σχετικό Issue
closes **ioniodi/sitegr#396**

### Σχετικό Pull Request στο minimal-ionio

### Συνεργάτες
@Vuxxs , @p19vrou

### Προτεινόμενες Αλλαγές
Όπως αναφέρεται στο [Video background on home page](https://github.com/ioniodi/sitegr/wiki/Video-background-on-home-page), στην τελευταία παράγραφο (Εναλλακτικές Προσεγγίσεις), υλοποίησα την πρόταση για δυναμική αλλαγή του background της κεντρικής σελίδας με βάση την συσκευή, δηλαδή background video όταν ο user agent είναι PC/Laptop και εμφάνιση jpeg image όταν ο user agent είναι Smartphone/Tablet. 

Η υλοποίηση έγινε με **Javascript** στο sitegr και κατά την φόρτωση της σελίδας, αν ο user agent είναι κινητό,  σβήνει το **iframe**  και θα το αντικαθιστά με **εικόνα**

Πρόσθεσα στο index.html το αρχείο της javascript (assets/js/index.js) και πρόσθεσα κατάλληλο css styling στο minimal-ionio για να φαίνεται σωστά η εικόνα.

..

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2022-04-19 12:14 UTC, epidrome commented
γιατί στέλνεις εδώ αντί για το θέμα το αρχείο js?

2022-04-21 14:33 UTC, p19zing commented
> γιατί στέλνεις εδώ αντί για το θέμα το αρχείο js?

@epidrome Μετέφερα το index.js στο minimal-ionio

2022-04-21 15:03 UTC, p19vrou commented
Δοκίμασα και από υπολογιστή και από κινητό, φαίνεται να λειτουργούν σωστά και τα δύο, ή τουλάχιστον δεν εμφανίστηκε πρόβλημα σε εμένα. Πιστεύω μπορείς να συνεχίσεις.

2022-04-22 13:16 UTC, epidrome commented
μήπως και η αναφορά στο index.js πρέπει να πάει κάπου στο θέμα σε κάποιο layout-include?

2022-04-30 14:26 UTC, epidrome requested changes

2022-04-30 14:26 UTC, epidrome commented on index.html
> +<script src="{{ base.url }}/assets/js/index.js">
μήπως η αναφορά στο index.js πρέπει να πάει κάπου στο θέμα σε κάποιο layout-include?

2022-04-30 14:47 UTC, closed without merging