Προσθή προγράμματος εξεταστικής 2022-2023(Ά και Γ εξάμηνο)
ioniodi/sitegr pull request #428
Opened 2023-05-09 15:17 UTC by Axileaszervos

### Σχετικό Issue
closes #[issue425](https://github.com/ioniodi/sitegr/issues/425)

### Σχετικό Pull Request
Σύνδεσμος σε σχετικό Pull Request στο all_collections που έχετε στείλει και πρέπει να επεξεργαστούμε σε συνδυασμό με αυτό εδώ
* [all_collections](https://github.com/ioniodi/all_collections/pull/73)
* [minimal-ionio](https://github.com/ioniodi/minimal-ionio/pull/47)

### Συνεργάτες
@Alxikan@nkanagno
Οι συνεργάτες θα κάνουν σχόλια ή θα αξιολογήσουν τις αλλαγές, κάντε mention @ τουλάχιστον δύο, όχι μέλη της ομάδας σας, αλλά κάποιους που δουλεύουν σε σχετικά θέματα, ώστε να πάρετε αντικειμένικη ανατροφοδότηση.

### Προτεινόμενες Αλλαγές
-- Σύντομη περιγραφή των επικείμενων αλλαγών:
   * Προσθήκη του προγράμματος εξεταστικής. Έχουν προστεθεί 3 νέες μεταβλητές( IN,DATE,HOUR) στα αντίστοιχα md files. Η μεταβλητή DATE προσδιορίζει την ημερομηνία εξέτασης του μαθήματος, η μεταβλητή IN την σειρά των μαθημάτων και η μεταβλητή HOUR την ώρα εξέτασης τους. Για την δημιουργία των πινάκων χρησιμοποιείται γλώσσα liquid. 
  
 
 ## Αρχεία του προγράμματος μου:
 * [ExamPro.html](https://github.com/Axileaszervos/minimal-ionio/blob/master/_includes/ExamPro.html)
 * [SemA.html](https://github.com/Axileaszervos/minimal-ionio/blob/master/_includes/SemA.html)
 * [SemC.html](https://github.com/Axileaszervos/minimal-ionio/blob/master/_includes/SemC.html)
 ## Μερικά αρχεία από τον φάκελο [all_collections](https://github.com/Axileaszervos/all_collections/tree/0a04575a2902f2895ec0d203ef006cd4551c9d0f) με τις νέες μεταβλητές:
  * [computer-architecture.md](https://github.com/Axileaszervos/all_collections/blob/0a04575a2902f2895ec0d203ef006cd4551c9d0f/_courses/computer-architecture.md)
  * [hci.md](https://github.com/Axileaszervos/all_collections/blob/0a04575a2902f2895ec0d203ef006cd4551c9d0f/_courses/hci.md)
  * [information-theory.md](https://github.com/Axileaszervos/all_collections/blob/0a04575a2902f2895ec0d203ef006cd4551c9d0f/_courses/information-theory.md)

## DEMO 
* ### [demo](https://axileaszervos-sitegr.netlify.app/exampro/)

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2023-05-19 13:23 UTC, nkanagno commented
Καλησπέρα συνάδελφε, η συνεισφορά σου μου φαίνεται πολύ καλή διότι πληρεί όλες τις προυποθέσεις για την δημιουργία μίας dynamic ιστοσελίδας, έχοντας χρησιμοποιήσει την γλώσσα shopify liquid προκειμένου να δημιουργήσεις πίνακες με δεδομένα που περιέχουν εσωτερικά links που κατευθύνονται άμεσα προς έτοιμα δεδομένα του all_collection. Η μόνη παρατήρηση που θα έκανα, θα ήταν η αφαίρεση της εικόνας  `Πιστοποιημένο Πρόγραμμα Σπουδών` που βρίσκεται κάτω δεξιά διότι είναι συνδεδεμένοι με link εκτός του sitegr και αν αλλαχτεί κάποια στιγμή στο μέλλον αυτό το link τότε θα αποτελέσει δυσλειτουργικό υπερσύνδεσμο με αποτέλεσμα να υπάρχει κάποιο bug στη ιστοσελίδα sitegr.

2023-05-19 13:32 UTC, nkanagno requested changes
Καλησπέρα συνάδελφε @Axileaszervos, η συνεισφορά σου μου φαίνεται πολύ καλή διότι πληρεί όλες τις προυποθέσεις για την δημιουργία μίας dynamic ιστοσελίδας, έχοντας χρησιμοποιήσει την γλώσσα shopify liquid προκειμένου να δημιουργήσεις πίνακες με δεδομένα που περιέχουν εσωτερικά links που κατευθύνονται άμεσα προς έτοιμα δεδομένα του all_collection. Η μόνη παρατήρηση που θα έκανα, θα ήταν η αφαίρεση της εικόνας  `Πιστοποιημένο Πρόγραμμα Σπουδών` που βρίσκεται κάτω δεξιά διότι είναι συνδεδεμένοι με link εκτός του sitegr και αν αλλαχτεί κάποια στιγμή στο μέλλον αυτό το link τότε θα αποτελέσει δυσλειτουργικό υπερσύνδεσμο με αποτέλεσμα να υπάρχει κάποιο bug στη ιστοσελίδα sitegr.

2023-05-19 18:46 UTC, Axileaszervos commented
> Καλησπέρα συνάδελφε @Axileaszervos, η συνεισφορά σου μου φαίνεται πολύ καλή διότι πληρεί όλες τις προυποθέσεις για την δημιουργία μίας dynamic ιστοσελίδας, έχοντας χρησιμοποιήσει την γλώσσα shopify liquid προκειμένου να δημιουργήσεις πίνακες με δεδομένα που περιέχουν εσωτερικά links που κατευθύνονται άμεσα προς έτοιμα δεδομένα του all_collection. Η μόνη παρατήρηση που θα έκανα, θα ήταν η αφαίρεση της εικόνας `Πιστοποιημένο Πρόγραμμα Σπουδών` που βρίσκεται κάτω δεξιά διότι είναι συνδεδεμένοι με link εκτός του sitegr και αν αλλαχτεί κάποια στιγμή στο μέλλον αυτό το link τότε θα αποτελέσει δυσλειτουργικό υπερσύνδεσμο με αποτέλεσμα να υπάρχει κάποιο bug στη ιστοσελίδα sitegr.

Σε ευχαριστώ πολύ συνάδελφε για τις παρατηρήσεις σου! Οι αλλαγές που πρότεινες πραγματοποιήθηκαν.

2023-05-23 09:14 UTC, epidrome commented
@Axileaszervos η αποδοχή του προηγούμενου αιτήματος δημιουργεί σύγκρουση 

επίσης, μήπως θα πρέπει να προστεθεί νέα σελίδα στην τεκμηρίωση;
https://github.com/ioniodi/sitegr/wiki/

2023-05-23 09:24 UTC, Axileaszervos commented
> @Axileaszervos η αποδοχή του προηγούμενου αιτήματος δημιουργεί σύγκρουση
> 
> επίσης, μήπως θα πρέπει να προστεθεί νέα σελίδα στην τεκμηρίωση; https://github.com/ioniodi/sitegr/wiki/
Καλησπέρα, εννοείτε στο repository minimal-ionio?

2023-05-23 09:28 UTC, closed without merging