Προσθήκη ανακοίνωσης από official site
ioniodi/sitegr pull request #57
Opened 2021-03-04 18:25 UTC by apostoloskp

### Σχετικό Issue
closes #**26**

### Προτεινόμενες Αλλαγές
-- 

--

..

### Υπενθυμίσεις
- [X] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [X] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [X] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-04 18:41 UTC, epidrome requested changes
- Δραστηριότητες Μελών

αντί για 

- Γενικές Ανακοινώσεις

2021-03-04 18:53 UTC, apostoloskp commented
> * Δραστηριότητες Μελών
> 
> αντί για
> 
> * Γενικές Ανακοινώσεις

Αλλαγή κατηγορίας σε "Δραστηριότητες Μελών"

2021-03-05 13:48 UTC, epidrome approved these changes

2021-03-06 07:20 UTC, c15pati approved these changes

2021-03-06 07:27 UTC, merged