Προσθήκη ανακοίνωσης από την σελίδα της σχολής
ioniodi/sitegr pull request #68
Opened 2021-03-04 21:45 UTC by Geoross

### Σχετικό Issue
closes #49

### Προτεινόμενες Αλλαγές
Προσθήκη ανακοίνωσης "Πρότυπα Ιατρεία Μνήμης για πρώτη φορά στην Ελλάδα" που δημοσιεύτηκε 20-02-2021 15:19.
https://p18test.netlify.app/posts/2021/02/20/protypa-iatreia/
..

### Υπενθυμίσεις
- [X] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [X] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [X] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-05 13:51 UTC, epidrome requested changes
1. διαγραφή της εικόνας

2. ετικέτες σύμφωνα με την ταξινόμηση στο γουηκι

2021-03-06 15:01 UTC, Geoross commented
1.Πρόσθεσα την εικόνα για να πετύχω μια καλύτερη (οπτικά) μεταφορά ανακοίνωσης από το κανονικό site, ωστόσο η εικόνα διεγράφη.
2. Σχετικά με τις ετικέτες έχω βάλει "conference" για το tag cloud. Ίσως δεν αντιλαμβάνομαι πλήρως αυτό που εννοείτε, θα μπορούσατε να γίνεται πιο αναλυτικός;

2021-03-07 10:15 UTC, epidrome requested changes
όλες οι ανακοινώσεις "γενικές" είναι

ας προσπαθήσουμε να βάλουμε λίγο πιο σχετικές ετικέτες, π.χ. 
https://github.com/ioniodi/sitegr/pull/57

2021-03-07 12:31 UTC, Geoross commented
Ωραία, ελπίζω τώρα να είναι εντάξει.

2021-03-08 09:02 UTC, c15pati approved these changes

2021-03-08 09:04 UTC, c15pati commented
Παρακαλώ πρόσθεσε όνομα, επώνυμο και ΑΜ στο PR

2021-03-08 15:05 UTC, epidrome approved these changes

2021-03-08 18:33 UTC, merged