Προσθήκη μαθήματος επιλογής Στ' εξαμήνου "Στοχαστική ανάλυση δεδομένων"
ioniodi/sitegr pull request #77
Opened 2021-03-05 16:57 UTC by p17kots

### Σχετικό Issue
closes #38

### Προτεινόμενες Αλλαγές
-- Αλλαγή 1
  Προστέθηκε το εν λόγω μάθημα στο πρόγραμμα σπουδών.
  [link](https://friendly-mirzakhani-6741df.netlify.app/courses/stochastic-data-analysis/)

..

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-05 17:35 UTC, epidrome requested changes
delete the _config.yml from the PR!

delete empty lines from the front-matter

2021-03-05 18:55 UTC, p17kots commented
OUPS
- [x] Empty lines deleted
- [x] Change at  _config.yml deleted

2021-03-06 07:43 UTC, c15pati approved these changes

2021-03-06 14:32 UTC, epidrome approved these changes

2021-03-06 14:32 UTC, merged