Προσθήκη περιεχομένου ΕΔΙΠ
ioniodi/sitegr pull request #86
Opened 2021-03-05 20:45 UTC by p18myro

### Σχετικό Issue
closes #**28**

### Προτεινόμενες Αλλαγές
-- Προσθήκη περιεχομένου ΕΔΙΠ Γιώργος Κατωμέρης

ΑΜ Π2018221
### [Εκτελέσιμο Netlify](https://sleepy-northcutt-a221a8.netlify.app/people/katomeris/)

..

### Υπενθυμίσεις
- [X] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [X] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [X] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-06 08:24 UTC, c15pati approved these changes

2021-03-07 10:23 UTC, epidrome requested changes
remove empty lines from front matter!

2021-03-07 13:44 UTC, p18myro reviewed
ok, I just removed them.

2021-03-08 15:09 UTC, epidrome approved these changes

2021-03-08 18:38 UTC, merged