Προσθήκη καθηγητή Μουρατίδη - close issue#45
ioniodi/sitegr pull request #87
Opened 2021-03-05 21:13 UTC by cyclenikolaos

### Σχετικό Issue
closes #**45**

### Προτεινόμενες Αλλαγές
-- Προσθήκη καθηγητή Χάρη Μουρατίδη στους επισκέπτες

## Εκτελέσιμο:
https://hopeful-rosalind-f96cf5.netlify.app/people/

### Υπενθυμίσεις
- [X] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [X] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [X] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-07 11:52 UTC, epidrome requested changes
η φώτο δεν φαίνεται γιατί δεν έχει γίνει εισαγωγή στο αρχείο author.yml

είτε να σβηστεί είτε να γίνει εισαγωγή στο παραπάνω αρχείο

2021-03-07 20:45 UTC, cyclenikolaos reviewed
Έκανα την απαραίτητη αλλαγή στο authors.yml ώστε να προβληθεί η φωτογραφία.

2021-03-08 18:39 UTC, c15pati approved these changes

2021-03-10 19:41 UTC, epidrome approved these changes

2021-03-11 19:15 UTC, merged