Προσθήκη Ανακοίνωσης
ioniodi/sitegr pull request #88
Opened 2021-03-05 21:16 UTC by giouliker

### Σχετικό Issue
closes #47 

### Προτεινόμενες Αλλαγές
Πρσθήκη της ανακοίνωσης με τίτλο "Ορισμός υπευθύνων για την ορθή και ενιαία εφαρμογή του πρωτοκόλλου διαχείρισης πιθανά ύποπτου ή επιβεβαιωμένου κρούσματος COVID-19"

[https://p18kera.netlify.app/posts/2020/09/30/upeuthinos-prwtokolou-covid19/](https://p18kera.netlify.app/posts/2020/09/30/upeuthinos-prwtokolou-covid19/)

ΑΜ: Π2018104
Κερασίδου Γεωργία

### Υπενθυμίσεις
- [X] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [X] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [X] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-07 11:55 UTC, epidrome requested changes
δεν βάζουμε ετικέτα στην τύχη!!!

https://github.com/ioniodi/sitegr/wiki/Taxonomy

2021-03-07 14:33 UTC, giouliker commented
Άλλαξα την ετικέτα σε "Αποφάσεις Οργάνων" και πρόσθεσα κατηγορία "ΑΝΑΚΟΙΝΩΣΕΙΣ"

2021-03-08 15:10 UTC, epidrome approved these changes

2021-03-08 18:40 UTC, c15pati approved these changes

2021-03-08 19:49 UTC, merged