Προσθήκη ανακοίνωσης "Διαβούλευση για το Σχέδιο του Εσωτερικού Κανονισμού του Ιονίου Πανεπιστημίου"
ioniodi/sitegr pull request #98
Opened 2021-03-06 12:09 UTC by p15anez

### Σχετικό Issue

closes #34 

### Προτεινόμενες Αλλαγές

-- Προσθήκη ανακοίνωσης "Διαβούλευση για το Σχέδιο του Εσωτερικού Κανονισμού του Ιονίου Πανεπιστημίου"

ΑΜ: Π2015097

Netlify: https://wizardly-noyce-934f26.netlify.app/posts/2021/02/22/diavouleusi-sxedio-eswterikou-kanonismou/
..

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-07 12:14 UTC, epidrome requested changes
tags?
https://github.com/ioniodi/sitegr/wiki/Taxonomy

2021-03-07 16:18 UTC, provopoulos approved these changes
Προστέθηκαν και οι ετικέτες. Σωστή δομή και εμφανίζεται κανονικά στις ανακοινώσεις.

2021-03-07 16:23 UTC, p15anez commented
Κύριε έβαλα και το categories που μου έλειπε πατάω re-request review για το τυπικό της υπόθεσης.

2021-03-07 16:40 UTC, provopoulos approved these changes

2021-03-08 17:54 UTC, c15pati approved these changes

2021-03-15 22:37 UTC, provopoulos commented
@epidrome
Small bump reminder in case the issue is lost in the shuffle.

2021-03-18 19:06 UTC, epidrome requested changes

2021-03-18 19:06 UTC, epidrome commented on all_collections/_posts/2021-02-22-Diavouleusi-sxedio-eswterikou-kanonismou.md
> + -
Αποφάσεις Οργάνων

2021-03-20 16:27 UTC, dimpram commented
Το link του netlify δεν δουλεύει :frowning_face:

2021-03-20 20:41 UTC, provopoulos commented
> 
> 
> Το link του netlify δεν δουλεύει ☹️

Must have died in transit 🙃

2021-03-21 18:00 UTC, p15anez commented
> Το link του netlify δεν δουλεύει ☹️

fixed

2021-03-30 12:25 UTC, epidrome approved these changes

2021-04-01 11:03 UTC, p15xiar approved these changes

2021-04-01 11:10 UTC, merged