Ενημέρωση/Διόρθωση μαθήματος Ανάκτηση Πληροφορίας
ioniodi/sitegr pull request #99
Opened 2021-03-06 12:21 UTC by p15xiar

### Σχετικό Issue
closes #69

### Προτεινόμενες Αλλαγές
-- Αλλαγή διδάσκοντα του μαθήματος Ανάκτηση Πληροφορίας.

-- Αλλαγή Περιγραφής του μαθήματος Ανάκτηση Πληροφορίας.

-- Προσθήκη ενός ακόμη συγγράμματος για το μάθημα Ανάκτηση Πληροφορίας.

Netlify: https://ioniounofficial.netlify.app/courses/information-retrieval/

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2021-03-07 12:16 UTC, epidrome requested changes
delete empty lines from front-matter!

2021-03-07 14:11 UTC, p15xiar commented
@epidrome Συγνώμη κύριε αλλα δεν μπορώ να καταλάβω σε ποιο αρχείο πρεπει να αφαιρέσω κενές γραμμές.

2021-03-07 16:36 UTC, provopoulos approved these changes
Με τις τελευταίες ενημερώσεις δεν υπάρχουν πια κενά. Σωστή δομή, εμφανίζεται κανονικά στα μαθήματα και το [προτεινόμενο](https://ioniounofficial.netlify.app/bibliography/isbn_978_960_402_116_1/) βιβλίο έχει προστεθεί και αυτό σωστά στη συλλογή.

2021-03-08 14:32 UTC, epidrome approved these changes

2021-03-08 18:42 UTC, c15pati approved these changes

2021-03-08 18:42 UTC, merged